### ISSUE TITLE
In the ASE dataset, how do I get the labels corresponding to the instances, and how do I convert them to point clouds based on depth images and rgb images

### ISSUE THREAD

**Issue by zhangzscn** [facebookresearch/projectaria_tools#1]

**Comment by skanti** [comment]
Hi @zhangzscn,
In order to back-project points from the depth map there are 3 steps to be done:
1. Unproject the pixels `(u,v)` of the raster into the ray direction using the `unproject` function
2. Replace the `z` value of the unprojected ray with the depth value `d` from the depth map of the corresponding pixel
3. Apply the `rig` and `world` transformation to transform the point cloud to world space

In a later update, we are considering to provide an example code that performs this process.

**Comment by zhangzscn** [comment]
How to parse instances images to obtain the corresponding object class？@skanti

**Comment by zhangzscn** [comment]
looking forward to it

**Comment by SeaOtocinclus** [comment]
@zhangzscn If you have all the answers to your question, please do consider closing this issue. Else please continue to ask questions and we will do our best to reply. Thank you.

**Comment by anassmu** [comment]
if you still need the answer to map depth, instances and rgb maps to pointclouds i did it :) don't hesitate liking the comment so i'll post the code

**Comment by anassmu** [comment]
if you still need help to create pointcloud from rgb and depth informations for ASE, like, i'll put the code :), you should load images, undistort them ( be defining a calibration instance depending on the model, is it fisheye or linear ..) then use the unproject function to get 3d points (scale them by depth) and add color information from rgb or instance images.
