### ISSUE TITLE
[ADT] Object actually not visible in frame

### ISSUE THREAD

**Issue by ZhihaoZhu** [facebookresearch/projectaria_tools#107]
Hi, I follow the art_quickstart_tutorial.ipynb to visualize GT 2d object bboxes given a specific frame. But in a lot of cases, those object can't even be observed in the frame. For instance: in the sequence `Apartment_release_work_seq136`, with select_timestamps_ns: `4851114903225`, stream_id: `StreamId("214-1")` and target_obj_id: `4469271893111727`, here is what I got in the visualization:
<img width="518" alt="Screenshot 2024-06-10 at 4 06 56 PM" src="https://github.com/facebookresearch/projectaria_tools/assets/20144308/b2469b1a-0d9e-4e10-8fee-b51361b40db1">

I use the following code to specify the target_obj_id:

```
bbox2d_with_dt = gt_provider.get_object_2d_boundingboxes_by_timestamp_ns(select_timestamps_ns, stream_id)

bbox2d_all_objects = bbox2d_with_dt.data()
    
all_instance_ids = list(bbox2d_all_objects.keys())
target_obj_id = all_instance_ids[0]
```

And I also checked its `visibility_ratio`, which shows 1.0, meaning full visibility. Does anyone know the issue?

**Comment by nickcharron** [comment]
Hi @ZhihaoZhu, thanks for posting your issue! 

I had a look at this dataset and the time you are querying for (4851114903225ns) is out of the time range of our ground truth data. All ADT sequences start collecting Aria data prior to starting the tracking system. This is because it takes a few seconds for Aria to get up and running and for the operators to disconnect Aria and get into view of the Optitrack cameras. When you query for any data using the ADT data provider, the default is to look for the nearest result. If you check the dtNs for that data, you'll see it's quite large. The solution to this is to always check that your query timestamp is within the range of the ground truth data using these two functions: [get_start_time_ns](https://github.com/facebookresearch/projectaria_tools/blob/main/projects/AriaDigitalTwinDatasetTools/python/AriaDigitalTwinDatasetToolsPyBind.h#L620), [get_end_time_ns](https://github.com/facebookresearch/projectaria_tools/blob/main/projects/AriaDigitalTwinDatasetTools/python/AriaDigitalTwinDatasetToolsPyBind.h#L625).

We show this in the tutorials, but it still seems to be an issue that many people encounter which makes me think I should just add a check within the code which outputs a warning when people haven't checked the bounds. I will try to implement this to hopefully solve this recurring problem :) 

Please let me know if this works! Thanks!

**Comment by ZhihaoZhu** [comment]
Hi @nickcharron , thank you for the reply! I verified the results, and they look reasonable, closing the issue
