### ISSUE TITLE
[ADT] Timestamp Offset

### ISSUE THREAD

**Issue by cdforigua05** [facebookresearch/projectaria_tools#14]
Hi !
I'm working with the ADT dataset on my research and I realized that for certain timestamps the offset between the the RGB image and the other data is huge. I understand that the time point from the GT data may not correspond to the exact same time points as the camera but is it normal to have a difference so high? In particular, I'm interested in using the depth maps. 
I attach an image that shows the problem.
To reproduce the issue I use the adt_quickstart_tutorial you provide and the sequence "Apartment_release_decoration_skeleton_seq131"

I'm using the stream_id "214-1" which is the id for the RGB image. Since my GT data is the depth maps, should I use another stream_id (stream ids: 345-1/2/3)? How do you recommend to extract the GT? Also I thought on just extract the image pairs that have a low difference time.

![Imagen 1](https://github.com/facebookresearch/projectaria_tools/assets/66923636/2a4a2962-05ba-4ce8-9b82-96f514661ab2)

**Comment by nickcharron** [comment]
Hi @cdforigua05, this is a great question. You are correct that the GT data might not correspond to exact image timestamps. We align the GT measurements to the SLAM camera timestamps. So the time difference between GT and SLAM images should be close to zero (only maybe rounding errors). However, since SLAM cameras and RGB cameras are very different (one is global shutter and the other is rolling shutter),  it's hard to perfectly align RGB and SLAM images at a hardware level. The upper time difference you are showing is the time difference between a SLAM image and an RGB image, and 92 microseconds is well within our expected range. 

The lower set of images is a different problem. I can't confirm without seeing your implementation, but it looks like you're querying image data before GT data is available. During the recordings, we start the Aria devices first, make sure they are collecting data, move into more visible parts of the room and then start the optitrack recording. We expect there to be a few seconds (maybe up to 30s) where there is Aria data with no GT data. We have two functions [getStartTimeNs](https://github.com/facebookresearch/projectaria_tools/blob/main/projects/AriaDigitalTwinDatasetTools/data_provider/AriaDigitalTwinDataProvider.h#L294) and [getEndTimeNs](https://github.com/facebookresearch/projectaria_tools/blob/main/projects/AriaDigitalTwinDatasetTools/data_provider/AriaDigitalTwinDataProvider.h#L298) which allow you to check that your query time is within the GT time range. 

To Answer this:

> Since my GT data is the depth maps, should I use another stream_id (stream ids: 345-1/2/3)

Depth data is stored according to the raw data stream IDs that were used to generate the depth data. Therefore if you want depth associated with RGB images, then use the RGB stream ID when querying depth (which I believe you are doing).

Hope this helps!

**Comment by cdforigua05** [comment]
Thanks @nickcharron, I tried to use the two functions you mentioned and so far it seems that the differences between the RGB images and the depth maps are close to 90 microseconds.
Thank you so much for  the help.
