### ISSUE TITLE
Retrieving Data Based on UTC Timestamps

### ISSUE THREAD

**Issue by Sainithin-bit** [facebookresearch/projectaria_tools#140]
I’m currently working with Meta Aria data and have encountered a challenge regarding the retrieval of data based on UTC timestamps. The documentation provides information on how to retrieve data based on the Aria internal timestamps (i.e., tracking_timestamp or DEVICE_TIME), but there is no guidance on directly retrieving data using UTC timestamps.

For my project, I need to synchronize the Meta Aria data with external sensors  based on UTC timestamps. Unfortunately, the current documentation does not explain how to achieve this, even though both tracking_timestamp and utc_timestamp are present in the open loop trajectory csv file.

When I upload the VRS file to MPS, I notice that the open-loop trajectory file contains UTC timestamps. However, the gaze information does not have UTC timestamps. This creates an inconsistency when I try to use gaze data in conjunction with the open-loop trajectory data, which includes UTC timestamps.

My question is: Is there a way to retrieve RGB images from the VRS file using UTC timestamps, as well as other data (e.g., gaze information) based on the same timestamp?

Could you provide guidance or add documentation about how to retrieve data from vrs file as well as MPS data based on UTC timestamps?

**Comment by chpeng-fb** [comment]
Hi, 

There is no API to directly query with UTC timestamp.
But here is a method to convert to UTC from the one to one correspondences between UTC and tracking timestamp. Since tracking timestamp is the same as device timestamp, you can directly use tracking timestamp instead to query RGB image. 
https://github.com/facebookresearch/projectaria_tools/issues/114
Hope this helps
