### ISSUE TITLE
[ADT] Projecting Points into Images

### ISSUE THREAD

**Issue by cdforigua05** [facebookresearch/projectaria_tools#15]
Hi!
First of all, I really appreciate the effort you put in the [ADT] dataset. I'm interested in using the 3D sparse-point clouds in the ADT dataset. Unlike the ASE dataset, the ADT dataset does not include the sparse point clouds information for each vrs file. I've been checking the documentation and I found a [projection tutorial in the ASE dataset](https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_synthetic_environments_dataset/ase_data_tools#part-3-projecting-points-into-images). However, I have a few questions:

1. I generated the point-cloud information for each vrs file in the ADT dataset through MPS in the Aria Desktop app. However, how can I map the trajectories from MPS to the information in the Aria Devices? Instead of loading the "aria_trajectory.csv" file, should I load the closed_loop_trajectory.csv that the MPS return in the AriaDataProvider? are the "tracking_timestamp_us" comparable between these two trajectory files? It seems as if the coordinate frames defers between these files. At the end of the day what I need is to project the 3D sparse points into the RGB images stored in the vis files and for that I need to be able to query the RGB images given the time_stamp in the closed_loop_trajectory.csv

3. I understand that the trajectories you provide in ADT are all in the same world coordinate frame. Is it possible for you to release the 3D sparse point cloud that shares the same coordinate frame with all the trajectories provided in the ADT dataset?

Thank you so much for your help.

**Comment by nickcharron** [comment]
Hi @cdforigua05, thanks for your question and for the positive feedback!

1. We haven't tested loading an MPS trajectory into the AriaDigitalTwinDataProvider. I believe this could work. A few things you'd have to be careful for: (a) don't load the object poses since those will be in the ADT Scene frame. (b) other GT data such as object 2D bounding boxes won't have the same time range since MPS start and end times will be different from that of ADT GT. However, I do not think you need to use ADT tools. You should be able to load your VRS file directly with the [VrsDataProvider](https://github.com/facebookresearch/projectaria_tools/blob/main/core/data_provider/VrsDataProvider.h) and load the trajectory with the [TrajectoryReader](https://github.com/facebookresearch/projectaria_tools/blob/main/core/mps/TrajectoryReaders.h), then you can query the VRS using the trajectory to get the images that correspond to trajectory measurements. 

2. It would be possible for us to generate the sparse 3D point clouds for ADT data in ADT's Scene frame, however, it would take some work so we would like to understand your need a little more to decide on the priority of this request vs others. Can you please tell us a little more about why you would like this data? Note that we do have [full depth maps](https://facebookresearch.github.io/projectaria_tools/docs/open_datasets/aria_digital_twin_dataset/data_format#ground-truth-data) already as part of the ADT data. Would this work for you instead of the semi-dense depth maps?

**Comment by cdforigua05** [comment]
Hi @nickcharron, thanks for your response

1. I'll try what you mention. At the end of the day, I need to have the full depth map, the RGB image and the sparse reprojection of the 3D point clouds all synchronized. But I think the depth maps would not be affected by the time ranges.
2. Sure! I'm interested in estimating the full depth maps using the information provided by the aria devices. Under that configuration, the full depth maps are our annotations. We want to use the reprojected points as an additional sparse input to help estimate the full depth maps.

**Comment by SeaOtocinclus** [comment]
@cdforigua05 Do you need more feedback, or can we close the issue?

**Comment by cdforigua05** [comment]
@SeaOtocinclus and @nickcharron I don't need more feedback at this time. Thank you so much for all your help. I'm closing the issue.

**Comment by nickcharron** [comment]
Hi @cdforigua05, I'm not sure if you've been following our releases, but I just wanted to inform you that we have  recently released MPS results for ADT sequences, inlcuding semidense pointclouds aligned to the ADT Scene frame. Please see the release notes for [v1.3.3](https://github.com/facebookresearch/projectaria_tools/releases/tag/1.3.3). You can download this data using the standard ADT dataset downloader
