### ISSUE TITLE
[ADT] Consistency of device poses

### ISSUE THREAD

**Issue by AlbertoJaenal** [facebookresearch/projectaria_tools#18]
Hi!
First of all, thanks to all the developers and the researchers that participated in the development of this amazing datasets.

I have a concern regarding Aria Digital Twin dataset, which I suppose that is derived from the poses of the device.

I am interested in creating a Structure-from-Motion model of the environment. For that, I extracted the images from one of the runs of the ADT dataset. I undistorted them (with a simple pinhole model) and I also computed the global pose of the camera in the next manner:
```
T_AriaceScene_AriaDevice = gt_provider.get_aria_3d_pose_by_timestamp_ns(timestamp_ns).data().transform_scene_device.matrix()
T_AriaDevice_AriaCamera = gt_provider.get_aria_transform_device_camera(stream_id).matrix()
T_AriaceScene_AriaCamera = T_AriaceScene_AriaDevice  @ T_AriaDevice_AriaCamera 
```
Then, I employed the poses (with the corrected timestamp when the image was taken) and the parameters of the camera as input model for COLMAP triangulation, in order to avoid running the costly reconstruction. To translate from Aria to COLMAP reference frames, I just needed a rotation in the z of -90 degrees (I also rotated the images).
The resulting model was really noisy (see below).
<img src="https://github.com/facebookresearch/projectaria_tools/assets/23337326/d3b8609a-df1f-42b9-a6bf-0729ca635644" width="600" />

- I have also tested to use the synthetic images instead of the real ones, but the result is pretty similar.
- I have also tried to employ the `get_interpolated_aria_3d_pose_at_timestamp_ns` to have a more precise estimation of the pose in the nanosecond where the image was captured, but the change is minimal (less than 10^-6 m).

My supposition is that this misalignment comes from the fact the poses were extracted from a MoCap device, which holds some error in global terms. 
Since synthetic images and depth were rendered, is there any way to obtain the synthetic pose they were obtained with? 

As a side try, I have exported the model to ROS, in order to visualize the pointclouds (aligned globally) from the depth with RViz, and they are also does not seem to be totally well aligned. There seem to be small errors in the pose that impede to see a perfect alignment and affect especially the far points in the pointlcoud.

**Comment by nickcharron** [comment]
Hi @AlbertoJaenal, thanks for your question. This is interesting work, thanks for sharing results!

> My supposition is that this misalignment comes from the fact the poses were extracted from a MoCap device, which holds some error in global terms.

Yes, our GT is mostly generated by the MoCap system, but also have some additional sources of error coming from our scene and object alignment processes, as well as our device to marker calibration. Please refer to [our paper](https://arxiv.org/abs/2306.06362) for more information. We did a thorough analysis of the expected end-to-end error in our dataset and the results were an average object pose error of 1.3 deg and 6.8 mm. Note that these error metrics describe the error of dynamic object poses relative to Aria images, therefore the error of just the Aria poses should be smaller. However, I suspect that these errors still might be too high to directly run SfM triangulation, so I would recommend re-running the full reconstruction and using the ADT poses as an initial estimate for each pose. I would also recommend you try to use the SLAM images for SfM, these should have lower errors since we align the trajectory to the SLAM images.

> Since synthetic images and depth were rendered, is there any way to obtain the synthetic pose they were obtained with?

The GT poses that we release are the same poses used to generate the synthetic data. I would also try the SLAM camera images for this as well.

Keep in mind that this dataset was mainly targetted for benchmarking object detection algorithms as well as image-to-image translation which have a much larger pose error thresholds compared to SLAM or SfM. We are working on improving our GT poses to allow our dataset to be more useful for applications such as yours. 

> As a side try, I have exported the model to ROS, in order to visualize the pointclouds (aligned globally) from the depth with RViz

This is great! Are you able to share results from this, or possibly a tool that others can use? This sounds like a great tool that the whole community could benefit from.

**Comment by AlbertoJaenal** [comment]
Thanks @nickcharron, for your quick answer!

>  However, I suspect that these errors still might be too high to directly run SfM triangulation, so I would recommend re-running the full reconstruction and using the ADT poses as an initial estimate for each pose. so I would recommend re-running the full reconstruction and using the ADT poses as an initial estimate for each pose. 

I see, so we share the intuition about this.  I will follow your advice, thanks!

> We are working on improving our GT poses to allow our dataset to be more useful for applications such as yours.

Nice to hear that! I will be up to any updates

> This is great! Are you able to share results from this, or possibly a tool that others can use? This sounds like a great tool that the whole community could benefit from.

I will work on cleaning the code to share it as soon as possible! 

I am closing this. Thanks again
