### ISSUE TITLE
Releases on GitHub not up to date

### ISSUE THREAD

**Issue by kabouzeid** [facebookresearch/projectaria_tools#60]
latest ist 1.3.0, but on PyPI it's 1.3.2

**Comment by SeaOtocinclus** [comment]
Hi @kabouzeid,
Thank you for your feedback.

This is expected, but due to some mismatch in our python wheels delivering process.
- Our last `code version` was 1.3.0, but we had some issues with our python wheels, so we generated two new minor versions on PyPI (that explains the jump to version 1.3.2).

Our pipeline to generate our python wheels has been improved and we don't expect this issue to happen any longer.

**Comment by SeaOtocinclus** [comment]
You can find our new release here https://github.com/facebookresearch/projectaria_tools/releases/tag/1.3.3 and see that we have a match for the tag and PyPI version https://pypi.org/project/projectaria-tools/1.3.3/
