### ISSUE TITLE
Why do you use f-theta fisheye lens for RGB camera?

### ISSUE THREAD

**Issue by tghim** [facebookresearch/projectaria_tools#63]
First of all, thank you for sharing your Project Aria tools.

But I'm curious why you used a fisheye lens instead of a regular lens.

I am personally researching Human Mesh Recovery, and in order to perform HMR of the second person from an egocentric view, the process of undistorting the fisheye lens image is necessary like [this work](https://rawalkhirodkar.github.io/egohumans/).

Another HMR dataset, EgoBody, collected data using HoloLens2, but this HMD did not use a fisheye lens, and I think the egocentric view is different from the fisheye.

Sorry for the long question. But I would be very grateful if you could reply.

**Comment by SeaOtocinclus** [comment]
Hello @tghim 
We are using fisheye lenses since they allow us to capture a large Fov (Field Of View).
Having a large field of view is helpful to understand the surrounding world of the users with a minimum number of cameras.

Note that regular lens (does not exists per se), they all have some distortion, they are often model with radial and tangetial correction.

To know more about Project Aria distortion model you can visit https://facebookresearch.github.io/projectaria_tools/docs/tech_insights/camera_intrinsic_models

To learn how to create undistorted image, you can visit https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/advanced_code_snippets/image_utilities#image-undistortion.

Note that EgoHuman is most likely using some GoPro that also have fishEye like lenses.

**Comment by SeaOtocinclus** [comment]
@tghim do you still have questions following our reply, else can you close the issue, thank you.
