### ISSUE TITLE
Software Architecture of Project Aria Tools

### ISSUE THREAD

**Issue by 0-1deathtouch** [facebookresearch/projectaria_tools#76]
Hello @nickcharron,

I'm working with Josiah on a school project and we've selected Project Aria Tools to work on. For the first part of the project we need to compare the actual architecture to the as-intended architecture. Is there any information you can share about the as-intended architecture? Either a design diagram or a text description would work great.

Thanks and take care,
Alanna Koser

**Comment by SeaOtocinclus** [comment]
Thank you for reaching out and asking questions.

As today our philosophy is to organize the code as the following:

- C++ code (host C++ and pybind code logic):
[projectaria_tools/core](https://github.com/facebookresearch/projectaria_tools/tree/main/core)

- Python (Python code - where pybind generated code will be added for installation):
[projectaria_tools/projectaria_tools](https://github.com/facebookresearch/projectaria_tools/tree/main/projectaria_tools)

- Documentation (Docusaurus):
[projectaria_tools/website](https://github.com/facebookresearch/projectaria_tools/tree/main/website)

- Projects (Dataset tooling, which use core code):
[projectaria_tools/projects](https://github.com/facebookresearch/projectaria_tools/tree/main/projects)

- Tools (Code samples (C++/ Python):
[projectaria_tools/tools](https://github.com/facebookresearch/projectaria_tools/tree/main/tools)

We may have some improvements to do in order to refactor/move some code in the `Tools` section in clear C++/Python folder that would be nice to take on as a first task by the community.
- If you are interested, I can describe the possible task in more details, and we can follow up on that

I also invite you to elaborate on your initial question and help us move toward your question (is it on Architectural design pattern ..., code architecture, ...)

**Comment by 0-1deathtouch** [comment]
Any info you could give on architectural design patterns or styles would be great, but if you don't have that info on major design decisions would work. Right now we are working off of info gleaned from the documentation pages, which is probably enough, but we'll take any additional information you could give us.

I'm asking the professor whether we can get credit for refactoring. I'll let you know once I hear back.

Thank you for your response!

**Comment by 0-1deathtouch** [comment]
Unfortunately we cannot get credit for refactoring. It needs to be new code. Let us know if you have ideas for additional functionality!

**Comment by SeaOtocinclus** [comment]
Would you like to implement a new python code sample?
- one interesting sample could be how to export VRS sound data to a WAV file (https://realpython.com/python-wav-files/)

I.e we are lacking code example to show how to manipulate sound data with our API and such feature would be welcomed

**Comment by SeaOtocinclus** [comment]
I would see it first as a code sample shared here https://github.com/facebookresearch/projectaria_tools/tree/main/tools/samples/python as `vrs_to_wav`
and then we can see how to migrate it to the API.

- Best would be to be able to support long wav files (https://www.ambisonia.com/Members/mleese/sony_wave64.pdf).

**Comment by jomandaman** [comment]
@SeaOtocinclus do you know if there is any public documentation on architectures or patterns used in the Open Source Project Aria? Specifically we're trying to identify and isolate design patterns like MVC, Factory model (which seem to be present), and also any security design patterns (Oauth?) as well. Any information is greatly appreciated!

**Comment by jomandaman** [comment]
@SeaOtocinclus @nickcharron @xiaqingp-meta Hey guys, so we've been working to create architecture diagrams of Project Aria to try and determine patterns and styles. So far we have a pretty good encapsulation of the MVC architecture. If anybody is interested to take a look or perhaps offer [feedback on our diagram](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=ProjectAriaMVC.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1uZPbQL5_x8eBYUZrFGPhrTW7OQ8AFmoj%26export%3Ddownload), we would be extremely grateful! 
![ProjectAria_MVC](https://github.com/facebookresearch/projectaria_tools/assets/51419063/cd6ad0f2-a01d-469a-8ae6-8cb101d6f6bd)

**Comment by SeaOtocinclus** [comment]
Closing this one, we will follow up on #95
