### ISSUE TITLE
ASE rotation problem

### ISSUE THREAD

**Issue by alphabet-lgtm** [facebookresearch/projectaria_tools#98]
I attempted to verify the rotation by calculating the UV coordinates from the point cloud's world coordinates (p_world). I obtained the point cloud's Pxyz from semidense_points.csv, UV coordinates from semidense_observations.csv, the camera's Txyz and Qxyzw from trajectory.csv, the camera's focal length and principal point from ase.get_ase_rgb_calibration(), and a rotation matrix T_device_from_camera from ase.get_ase_rgb_calibration().get_transform_device_camera().to_matrix(). Additionally, I distorted the image to normal using projectaria_tools.core.calibration.distort_by_calibration(raw_image, pinhole, device). Although the results might not be perfectly consistent due to the distortion correction, they should be somewhat similar. However, the discrepancy is significant: my result is (996.20, -17.32), while the provided result is (580.13, 219.96).

Here is my code:

```
R = qvec2rotmat(qvec)
T = np.array([camerainfo.tx_world_device[i], camerainfo.ty_world_device[i], camerainfo.tz_world_device[i]])
focal = deviceinfo.get_focal_lengths()
cx, cy = deviceinfo.get_principal_point()

T_world_from_device = np.eye(4)
T_world_from_device[:3, :3] = R
T_world_from_device[:3, 3] = T
T_device_from_world = np.linalg.inv(T_world_from_device)
T_device_from_camera = deviceinfo.get_transform_device_camera().to_matrix()
T_camera_from_device = np.linalg.inv(T_device_from_camera)
point_dev = transform_3d_points(T_device_from_world, [point])
point_rgb = transform_3d_points(T_camera_from_device, point_dev)[0]

x = (point_rgb[0] / point_rgb[2] * focal[0]) + cx
y = (point_rgb[1] / point_rgb[2] * focal[1]) + cy

def qvec2rotmat(qvec):
    return np.array([
        [1 - 2 * qvec[2] ** 2 - 2 * qvec[3] ** 2,
         2 * qvec[1] * qvec[2] - 2 * qvec[0] * qvec[3],
         2 * qvec[3] * qvec[1] + 2 * qvec[0] * qvec[2]],
        [2 * qvec[1] * qvec[2] + 2 * qvec[0] * qvec[3],
         1 - 2 * qvec[1] ** 2 - 2 * qvec[3] ** 2,
         2 * qvec[2] * qvec[3] - 2 * qvec[0] * qvec[1]],
        [2 * qvec[3] * qvec[1] - 2 * qvec[0] * qvec[2],
         2 * qvec[2] * qvec[3] + 2 * qvec[0] * qvec[1],
         1 - 2 * qvec[1] ** 2 - 2 * qvec[2] ** 2]])

def transform_3d_points(transform, points):
    N = len(points)
    points_h = np.concatenate([points, np.ones((N, 1))], axis=1)
    transformed_points_h = (transform @ points_h.T).T
    transformed_points = transformed_points_h[:, :-1]
    return transformed_points
```
Is there anything incorrect? Thank you.

**Comment by suvampatra** [comment]
At the moment, there is no way of verifying these. 

This is because since the semidense points are generated and hence observed from left/right slam cameras, hence the U, V coordinates that you picked up in the observation files are either from the left/right slam cameras as stated [here](https://facebookresearch.github.io/projectaria_tools/docs/data_formats/mps/slam/mps_pointcloud). 
cameraSerial = 16 implies left and cameraSerial =17 implies right slam cameras respectively. 


The trajectory frame id would come from the time stamp in frameCaptureTimestamp

So in order, to verify these, we will also need the calibration parameters for left and right cameras which is not there at the moment. This is the reason they are not matching. I hope this clarifies the situation.

**Comment by alphabet-lgtm** [comment]
> At the moment, there is no way of verifying these.
> 
> This is because since the semidense points are generated and hence observed from left/right slam cameras, hence the U, V coordinates that you picked up in the observation files are either from the left/right slam cameras as stated [here](https://facebookresearch.github.io/projectaria_tools/docs/data_formats/mps/slam/mps_pointcloud). If you have loaded these with the mps.read_point_observations then you will notice that they will have a cameraSerial field and a frameCaptureTimestamp field as well. To explain these,
> 
> cameraSerial = 16 implies left and cameraSerial =17 implies right slam cameras respectively.
> 
> The trajectory frame id would come from the time stamp in frameCaptureTimestamp
> 
> So in order, to verify these, we will also need the calibration parameters for left and right cameras which is not there at the moment. This is the reason they are not matching. I hope this clarifies the situation.

Thank you for your response. I understand what you mean. I have another question: does my code correctly get the point cloud's U, V coordinates in the RGB camera? As you know, projectaria_tools.core.calibration.distort_by_calibration(raw_image, pinhole, device) produces a 701x701 image, but my result is (996.20, -17.32).

**Comment by suvampatra** [comment]
This is interesting, Will have a look at it. 

But meanwhile I will also suggest using the built in quaternion to rotation matrix estimation instead of writing yours. Here is an example from quat_xyzw -> rot_matrix

`from scipy.spatial.transform import Rotation as R
  rot_matrix = R.from_quat(quat_xyzw).as_matrix()
  rot_matrix = np.array(rot_matrix)`

see the example here: [example](https://github.com/facebookresearch/projectaria_tools/blob/main/projects/AriaSyntheticEnvironment/tutorial/code_snippets/readers.py)

**Comment by alphabet-lgtm** [comment]
> This is interesting, Will have a look at it.
> 
> But meanwhile I will also suggest using the built in quaternion to rotation matrix estimation instead of writing yours. Here is an example from **quat_xyzw -> rot_matrix**
> 
> `import numpy as np` `from scipy.spatial.transform import Rotation as R` `rot_matrix = R.from_quat(quat_xyzw).as_matrix()` `rot_matrix = np.array(rot_matrix)`
> 
> see the example here: [example](https://github.com/facebookresearch/projectaria_tools/blob/main/projects/AriaSyntheticEnvironment/tutorial/code_snippets/readers.py)

Thank you for your suggestion and reply! I tried your suggestion (using scipy.spatial.transform.Rotation), and I got the same rotation matrix as with my function. This confirms that the rotation matrix does not influence the final U, V coordinates. Therefore, I believe there is still something wrong with my code.

**Comment by alphabet-lgtm** [comment]
> This is interesting, Will have a look at it.
> 
> But meanwhile I will also suggest using the built in quaternion to rotation matrix estimation instead of writing yours. Here is an example from **quat_xyzw -> rot_matrix**
> 
> `import numpy as np` `from scipy.spatial.transform import Rotation as R` `rot_matrix = R.from_quat(quat_xyzw).as_matrix()` `rot_matrix = np.array(rot_matrix)`
> 
> see the example here: [example](https://github.com/facebookresearch/projectaria_tools/blob/main/projects/AriaSyntheticEnvironment/tutorial/code_snippets/readers.py)

I got the correct result, thank you! I realized that I made a mistake: the SLAM camera is not the same as the RGB camera, so points that are out of range should just be discarded.

![image](https://github.com/facebookresearch/projectaria_tools/assets/58328881/0409d81c-9a26-408c-b119-d3d29cb9b64f)

**Comment by suvampatra** [comment]
@alphabet-lgtm  I also investigated on my side, and good to see you reached to the same conclusion as me. 
Two things here:
1: They aren't the same cameras
2. the views though have an area of overlap are not the same, hence some portion of the slam camera is boiund to end up outside the bounds of the rgb camera and hence you get a projection outside boundary. good that you verifed using a projection.
This issue is now resolved.
